vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        animals:
            uri_prefix: /images/animals
            upload_destination: '%kernel.project_dir%/public/images/animals'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


        habitats:
            uri_prefix: /images/habitats
            upload_destination: '%kernel.project_dir%/public/images/habitats'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        services:
            uri_prefix: /images/services
            upload_destination: '%kernel.project_dir%/public/images/services'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


        images:
            uri_prefix: /images/images
            upload_destination: '%kernel.project_dir%/public/images/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
